:: Update Service Configurations
aws lambda update-function-configuration --function-name email --timeout 200 --environment "Variables={AAK=AKIA3WG626624PXNXZXT, ASAK=ABCWr1iBdQLSGUDzHtn9vx2NJv4wc0/+APcfuIaY, MCS=mongodb+srv://root:root@capstone.ailclxg.mongodb.net/?retryWrites=true&w=majority, AEU=https://sqs.us-east-1.amazonaws.com/803626219445/deficit_queue.fifo, SE=ldcoding1203@gmail.com, SP=gqmraedaumvwxwbb}"
aws lambda update-function-configuration --function-name init --timeout 200 --environment "Variables={AAK=AKIA3WG626624PXNXZXT, ASAK=ABCWr1iBdQLSGUDzHtn9vx2NJv4wc0/+APcfuIaY, MCS=mongodb+srv://root:root@capstone.ailclxg.mongodb.net/?retryWrites=true&w=majority}"
aws lambda update-function-configuration --function-name log_create --timeout 200 --environment "Variables={AAK=AKIA3WG626624PXNXZXT, ASAK=ABCWr1iBdQLSGUDzHtn9vx2NJv4wc0/+APcfuIaY, MCS=mongodb+srv://root:root@capstone.ailclxg.mongodb.net/?retryWrites=true&w=majority}"
aws lambda update-function-configuration --function-name log_delete --timeout 200 --environment "Variables={AAK=AKIA3WG626624PXNXZXT, ASAK=ABCWr1iBdQLSGUDzHtn9vx2NJv4wc0/+APcfuIaY, MCS=mongodb+srv://root:root@capstone.ailclxg.mongodb.net/?retryWrites=true&w=majority}"
aws lambda update-function-configuration --function-name log_update --timeout 200 --environment "Variables={AAK=AKIA3WG626624PXNXZXT, ASAK=ABCWr1iBdQLSGUDzHtn9vx2NJv4wc0/+APcfuIaY, MCS=mongodb+srv://root:root@capstone.ailclxg.mongodb.net/?retryWrites=true&w=majority}"
aws lambda update-function-configuration --function-name log_read --timeout 200 --environment "Variables={AAK=AKIA3WG626624PXNXZXT, ASAK=ABCWr1iBdQLSGUDzHtn9vx2NJv4wc0/+APcfuIaY, MCS=mongodb+srv://root:root@capstone.ailclxg.mongodb.net/?retryWrites=true&w=majority}"
aws lambda update-function-configuration --function-name user_create --timeout 200 --environment "Variables={AAK=AKIA3WG626624PXNXZXT, ASAK=ABCWr1iBdQLSGUDzHtn9vx2NJv4wc0/+APcfuIaY, MCS=mongodb+srv://root:root@capstone.ailclxg.mongodb.net/?retryWrites=true&w=majority}"
aws lambda update-function-configuration --function-name user_delete --timeout 200 --environment "Variables={AAK=AKIA3WG626624PXNXZXT, ASAK=ABCWr1iBdQLSGUDzHtn9vx2NJv4wc0/+APcfuIaY, MCS=mongodb+srv://root:root@capstone.ailclxg.mongodb.net/?retryWrites=true&w=majority}"
aws lambda update-function-configuration --function-name user_login --timeout 200 --environment "Variables={AAK=AKIA3WG626624PXNXZXT, ASAK=ABCWr1iBdQLSGUDzHtn9vx2NJv4wc0/+APcfuIaY, MCS=mongodb+srv://root:root@capstone.ailclxg.mongodb.net/?retryWrites=true&w=majority}"
aws lambda update-function-configuration --function-name user_update --timeout 200 --environment "Variables={AAK=AKIA3WG626624PXNXZXT, ASAK=ABCWr1iBdQLSGUDzHtn9vx2NJv4wc0/+APcfuIaY, MCS=mongodb+srv://root:root@capstone.ailclxg.mongodb.net/?retryWrites=true&w=majority}"
pause